### PR TITLE
Update contracts

### PR DESCRIPTION
**Pull request by yuichiroaoki**
* pass byte data and remove Router contract
* tests with 1inch routes
* tests with latest blocks

### CODE REVIEW

**Comment by adedade** [comment]
Looks great, how can I help you land this PR?

**Comment by yuichiroaoki** [comment]
@adedade Thank you for asking. Yeah this PR seems ok, but the bot code needs to be changed since the parameters of the flash loan function has changed.
https://github.com/yuichiroaoki/poly-flashloan-bot/pull/47

If the bot one looks okay, I will merge both.

**Comment by adedade** [comment]
Hey @yuichiroaoki, I think for breaking changes e.g. contract change and therefore bot code needs to change, you might want want to push a new release/tag so that people know which version of the contract works with a specific version of the bot!

**Comment by yuichiroaoki** [comment]
@adedade Good point! I did it.

**Pull request merged**
